// Generated by CoffeeScript 1.4.0

/*!
    jQuery plugin for "jquery-1.9.1".

    Copyright see require on https://github.com/thaibault/require

    Conventions see require on https://github.com/thaibault/require

    @author t.sickert@gmail.com (Torben Sickert)
    @version 1.0 stable
    @fileOverview
    This module provides common logic for the whole webpage.
*/


/**
    @name jQuery
    @see www.jquery.com
*/


(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  (function(jQuery) {
    /**
        @memberOf jQuery
        @class
    */

    var Website;
    Website = (function(_super) {

      __extends(Website, _super);

      function Website() {
        return Website.__super__.constructor.apply(this, arguments);
      }

      Website.prototype.__name__ = 'Website';

      Website.prototype.__googleAnalyticsCode = "(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','//www.google-analytics.com/analytics.js','ga');ga('create', '{1}', 'github.io');ga('send', 'pageview');";

      /**
          Saves default options for manipulating the default behaviour.
      
          @property {Object}
      */


      Website.prototype._options = {};

      /**
          Saves default options for manipulating the default behaviour.
      
          @property {Object}
      */


      Website.prototype._parentOptions = {
        logging: false,
        domNodeSelectorPrefix: 'body.{1}',
        onVieportMovesToTop: jQuery.noop(),
        onVieportMovesAwayFromTop: jQuery.noop(),
        onChangeToDesktopMode: jQuery.noop(),
        onChangeToTabletMode: jQuery.noop(),
        onChangeToSmartphoneMode: jQuery.noop(),
        onSwitchSection: jQuery.noop(),
        onStartUpAnimationComplete: jQuery.noop(),
        addtionalPageLoadingTimeInMilliseconds: 0,
        mediaQueryCssIndicatorStyleType: 'border-left-style',
        trackingCode: 'UA-0-0',
        mediaQueryCssIndicator: {
          desktop: 'dashed',
          tablet: 'solid',
          smartphone: 'dotted'
        },
        domNodes: {
          topDomNode: 'div.navigation-bar',
          navigationOnTopIndicatorClass: 'on-top',
          scrollToTopButtons: 'a[href="#top"]',
          startUpAnimationClassPrefix: '.start-up-animation-number-',
          windowLoadingCover: 'div.window-loading-cover',
          windowLoadingSpinner: 'div.window-loading-cover div'
        },
        startUpFadeInOptions: {
          easing: 'swing',
          duration: 'slow'
        },
        windowLoadingCoverFadeOutOptions: {
          easing: 'swing',
          duration: 'slow'
        },
        startUpAnimationElementDelayInMiliseconds: 100,
        windowLoadingSpinnerOptions: {
          lines: 9,
          length: 23,
          width: 11,
          radius: 40,
          corners: 1,
          rotate: 75,
          color: '#000',
          speed: 1.1,
          trail: 58,
          shadow: false,
          hwaccel: false,
          className: 'spinner',
          zIndex: 2e9,
          top: 'auto',
          left: 'auto'
        }
      };

      /**
          Holds all needed dom nodes.
      
          @property {Object}
      */


      Website.prototype._domNodes = {};

      /**
          Determines weather the view port is on top of the page.
      
          @property {Boolean}
      */


      Website.prototype._vieportIsOnTop = true;

      /**
          Describes the current mode defined by the css media queries.
      
          @property {String}
      */


      Website.prototype._currentMediaQueryMode = '';

      /**
          @description Initializes the interactive webapp.
      
          @param {Object} options An options object.
      
          @returns {jQuery.Tools} Returns the current instance.
      */


      Website.prototype.initialize = function(options) {
        this._options = jQuery.extend(true, this._parentOptions, this._options);
        Website.__super__.initialize.call(this, options);
        this._domNodes = this.grapDomNodes(this._options.domNodes);
        this._options.windowLoadingCoverFadeOutOptions.always = this.getMethod(this._handleStartUpEffects);
        this._domNodes.windowLoadingSpinner.spin(this._options.windowLoadingSpinnerOptions);
        this._bindScrollEvents()._domNodes.parent.show();
        this._domNodes.window.ready(this.getMethod(this._removeLoadingCover));
        return this._addNavigationEvents()._addMediaQueryChangeEvents()._triggerWindowResizeEvents()._handleGoogleAnalytics(this._options.trackingCode);
      };

      /**
          @description This method triggers if the vieport moves to top.
      
          @returns {jQuery.Tools} Returns the current instance.
      */


      Website.prototype._onVieportMovesToTop = function() {
        var _this = this;
        this._domNodes.scrollToTopButtons.animate({
          bottom: '+=30',
          opacity: 0
        }, {
          duration: 'normal',
          always: function() {
            return _this._domNodes.scrollToTopButtons.css('bottom', '-=30');
          }
        });
        return this;
      };

      /**
          @description This method triggers if the vieport moves away from
                       top.
      
          @returns {jQuery.Tools} Returns the current instance.
      */


      Website.prototype._onVieportMovesAwayFromTop = function() {
        this._domNodes.scrollToTopButtons.css({
          bottom: '+=30',
          display: 'block',
          opacity: 0
        }).animate({
          bottom: '-=30',
          queue: false,
          opacity: 1
        }, {
          duration: 'normal'
        });
        return this;
      };

      /**
          @description This method triggers if the responsive design
                       switches to desktop mode.
      
          @returns {jQuery.Tools} Returns the current instance.
      */


      Website.prototype._onChangeToDesktopMode = function() {
        return this;
      };

      /**
          @description This method triggers if the responsive design
                       switches to tablet mode.
      
          @returns {jQuery.Tools} Returns the current instance.
      */


      Website.prototype._onChangeToTabletMode = function() {
        return this;
      };

      /**
          @description This method triggers if the responsive design
                       switches to smart phone mode.
      
          @returns {jQuery.Tools} Returns the current instance.
      */


      Website.prototype._onChangeToSmartphoneMode = function() {
        return this;
      };

      /**
          @description This method triggers if we change the current section.
      
          @returns {jQuery.Tools} Returns the current instance.
      */


      Website.prototype._onSwitchSection = function() {
        return this;
      };

      /**
          @description This method is complete if last startup animation
                       was initialized.
      
          @returns {jQuery.Tools} Returns the current instance.
      */


      Website.prototype._onStartUpAnimationComplete = function() {
        return this;
      };

      /**
          @description This method adds triggers for responsive design
                       switches.
      
          @returns {jQuery.Tools} Returns the current instance.
      */


      Website.prototype._addMediaQueryChangeEvents = function() {
        this.on(this._domNodes.window, 'resize', this.getMethod(this._triggerWindowResizeEvents));
        return this;
      };

      /**
          @description This method triggers if the responsive design
                       switches its mode.
      
          @returns {jQuery.Tools} Returns the current instance.
      */


      Website.prototype._triggerWindowResizeEvents = function() {
        var _this = this;
        jQuery.each(this._options.mediaQueryCssIndicator, function(mode, cssValue) {
          if (_this._domNodes.parent.css(_this._options.mediaQueryCssIndicatorStyleType) === cssValue && mode !== _this._currentMediaQueryMode) {
            _this._currentMediaQueryMode = mode;
            return _this.fireEvent.apply(_this, [_this.stringFormat('changeTo{1}Mode', mode.substr(0, 1).toUpperCase() + mode.substr(1)), false, _this].concat(_this.argumentsObjectToArray(arguments)));
          }
        });
        return this;
      };

      /**
          @description This method triggers if viewport arrives at special
                       areas.
      
          @returns {jQuery.Tools} Returns the current instance.
      */


      Website.prototype._bindScrollEvents = function() {
        var _this = this;
        this.on(window, 'scroll', function() {
          if (_this._domNodes.window.scrollTop()) {
            if (_this._vieportIsOnTop) {
              _this._vieportIsOnTop = false;
              return _this.fireEvent.apply(_this, ['vieportMovesAwayFromTop', false, _this].concat(_this.argumentsObjectToArray(arguments)));
            }
          } else if (!_this._vieportIsOnTop) {
            _this._vieportIsOnTop = true;
            return _this.fireEvent.apply(_this, ['vieportMovesToTop', false, _this].concat(_this.argumentsObjectToArray(arguments)));
          }
        });
        return this;
      };

      /**
          @description This method triggers after window is loaded.
      
          @returns {jQuery.Tools} Returns the current instance.
      */


      Website.prototype._removeLoadingCover = function() {
        var _this = this;
        window.setTimeout(function() {
          /*
                                  Hide startup animation dom nodes to show them step
                                  by step.
          */
          jQuery('[class^="' + _this.sliceDomNodeSelectorPrefix(_this._options.domNodes.startUpAnimationClassPrefix).substr(1) + '"]').hide();
          return _this._domNodes.windowLoadingCover.fadeOut(_this._options.windowLoadingCoverFadeOutOptions);
        }, this._options.addtionalPageLoadingTimeInMilliseconds);
        return this;
      };

      /**
          @description This method handles the given start up effect step.
      
          @param {Number} elementNumber The current start up step.
      
          @returns {jQuery.Tools} Returns the current instance.
      */


      Website.prototype._handleStartUpEffects = function(elementNumber) {
        var _this = this;
        this._domNodes.windowLoadingSpinner.spin(false);
        if (!jQuery.isNumeric(elementNumber)) {
          elementNumber = 1;
        }
        window.setTimeout(function() {
          jQuery(_this._options.domNodes.startUpAnimationClassPrefix + elementNumber).fadeIn(_this._options.startUpFadeInOptions);
          if ((jQuery(_this._options.domNodes.startUpAnimationClassPrefix + (elementNumber + 1)).length)) {
            return _this._handleStartUpEffects(elementNumber + 1);
          } else if (window.location.href.indexOf('#') !== -1) {
            return _this.fireEvent('startUpAnimationComplete');
          }
        }, this._options.startUpAnimationElementDelayInMiliseconds);
        return this;
      };

      /**
          @description This method adds triggers to switch section.
      
          @returns {jQuery.Tools} Returns the current instance.
      */


      Website.prototype._addNavigationEvents = function() {
        var _this = this;
        this._domNodes.window.hashchange(function() {
          return _this.fireEvent('switchSection', false, _this, window.location.hash);
        });
        return this._handleScrollToTopButton();
      };

      /**
          @description Adds trigger to scroll top buttons.
      
          @returns {jQuery.Tools} Returns the current instance.
      */


      Website.prototype._handleScrollToTopButton = function() {
        var _this = this;
        this.on(this._domNodes.scrollToTopButtons, 'click', function(event) {
          event.preventDefault();
          return _this._scrollToTop();
        });
        this._domNodes.scrollToTopButtons.hide();
        return this;
      };

      /**
          @description Scrolls to top of page. Runs the given function
                       after viewport arrives.
      
          @param {Function} onAfter Callback to call after effect has
                                    finished.
      
          @returns {jQuery.Tools} Returns the current instance.
      */


      Website.prototype._scrollToTop = function(onAfter) {
        var distanceToScroll, distanceToTop, menuHeight;
        if (onAfter == null) {
          onAfter = jQuery.noop();
        }
        distanceToTop = this._domNodes.window.scrollTop();
        menuHeight = this._domNodes.topDomNode.find('div.navbar').outerHeight();
        distanceToScroll = distanceToTop + menuHeight;
        if (distanceToTop < menuHeight) {
          distanceToScroll = distanceToScroll + menuHeight - distanceToTop;
        }
        jQuery.scrollTo({
          top: "-=" + distanceToScroll + "px",
          left: '-=0'
        }, {
          duration: distanceToScroll,
          onAfter: onAfter
        });
        return this;
      };

      /**
          @description Scrolls to top of page. Runs the given function
                       after vieport arrives.
      
          @param {String} trackingCode Google's javaScript embedding code
                                       snippet.
      
          @returns {jQuery.Tools} Returns the current instance.
      */


      Website.prototype._handleGoogleAnalytics = function(trackingCode) {
        window["eval"](this.stringFormat(this.__googleAnalyticsCode, trackingCode));
        return this;
      };

      return Website;

    })(jQuery.Tools["class"]);
    /** @ignore
    */

    jQuery.Website = function() {
      var self;
      self = new Website;
      return self._controller.apply(self, arguments);
    };
    /** @ignore
    */

    return jQuery.Website["class"] = Website;
  }).call(this, this.jQuery);

}).call(this);
